config/routes.rb
Rails.application.routes.draw do
  get 'illustrator/mockup'
  get 'illustrator/mockuphand'
  get 'illustrator/functional'

  root 'application#index'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def index
    
  end
end

app/controllers/illustrator_controller.rb
class IllustratorController < ApplicationController
  def advanced
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/illustrator_helper.rb
module IllustratorHelper
end

app/helpers/magic_helper.rb
module MagicHelper
end

app/helpers/tab_helper.rb
module TabHelper
end

app/views/application/_back_to_root.html.haml
:scss
    #back-button{
        position: absolute;
        z-index: 100;
        top: 15px;
        left: 15px;
    }
    
= link_to root_path, id: "back-button", class: "btn btn-primary" do
    %span.glyphicon.glyphicon-chevron-left

app/views/application/index.html.haml
.container-fluid.np
    .col-xs-12.col-sm-6.np
        .panel.panel-primary
            .panel-heading 
                %b
                    Practicum 4
                Mirror, mirror
            .panel-body
                %ul.list-group
                    %li.list-group-item 
                        = link_to illustrator_mockup_path do
                            %b Illustrator 201
                            Mockup (auto Generated)
                            %span.pull-right.glyphicon.glyphicon-chevron-right
                    %li.list-group-item 
                        = link_to illustrator_mockuphand_path do
                            %b Illustrator 201
                            Mockup (by Hand)
                            %span.pull-right.glyphicon.glyphicon-chevron-right
                    %li.list-group-item 
                        = link_to illustrator_functional_path do
                            %b Illustrator 201
                            Functional
                            %span.pull-right.glyphicon.glyphicon-chevron-right
                   
                   
            .panel-footer
                CS160 - Intro to UI Design and Development
   

app/views/illustrator/functional.html.haml
:coffeescript
    $ ->
        $('#unlocked').hide()
        paper = Utility.paperSetup('spin-to-unlock')
        animate = (options, animationHandler)->
            def = { duration: 1000}
            options = _.extend def, options
            frames = _.range(0, options.duration, 33.33)
            _.each frames, (frame, i)->
                p = i/(frames.length - 1)
                animationHandler(p, frame)
        
        fadeOutAnimation = (options)->
            animate options, (p, frame)->
                f = ->
                    options.path.opacity = 1-p
                _.delay f, frame
                
        blinkAnimation = (options)->
            animate options, (p, frame)->
                f = ->
                    op = 0.5 * (1 + Math.cos(Math.PI * 2 * p))
                    options.path.opacity = op
                _.delay f, frame
        
        classify_window = (tw)->
            diff = 0
            _.each tw, (sample, i)->
                if i == 0 then return
                previous = tw[i - 1]
                diff = diff + (sample - previous)
            if Math.abs(diff) > 100
                $('#spin-to-unlock').trigger("spin")
            else
                $('#spin-to-unlock').trigger("spinattempt")
        
        time_window = []
        onSVGLoad = (svg)->
            svg.fitBounds(paper.view.bounds.expand(-100))
            window.svg = svg
            window.spinner = svg.getItem({name: 'logo-accent'})
            base = svg.getItem({name: 'logo-base'})
            spintext = svg.getItem({name: 'spin-text'})
            spintrack = new paper.Path.Circle
                radius: base.radius
                parent: base.parent
                position: base.position.clone()
            
            spinner.onMouseDown = (event)->
                trackPt = spintrack.getNearestPoint(event.point)

            spinner.onMouseDrag = (event)->
                trackPt = spintrack.getNearestPoint(event.point)
                angle = trackPt.subtract(base.position).angle
                time_window.push(angle)
                spinner.position = trackPt
                if time_window.length > 20
                    classify_window(time_window)
                    time_window = time_window.slice(-10)
                    
            spinOnce = _.once ()->
                console.log "SPINNED"
                fadeOutAnimation
                    path: spintext
                    duration: 500
                fadeOutAnimation
                    path: spinner.parent
                    duration: 700
                $( "#unlocked" ).animate
                    height: "toggle"
                , 1000, ()->
                    console.log "UNLOCKED"
                $('#logo').fadeOut()
                spinAttemptHandler = ()->
                    console.log "UNLOCK UNBOUND"
            spinHandler = ()->
                spinOnce()
                  
                  
              
            spinAttemptHandler = ()->
                console.log "SPIN FAIL"
                blinkAnimation
                    path: spintext
                    duration: 1000
                
            $('#spin-to-unlock').on('spin', spinHandler)
            $('#spin-to-unlock').on('spinattempt', spinAttemptHandler)
                
        paper.project.importSVG "/assets/slide-to-unlock.svg", onSVGLoad
        
:scss
    $background: #00A79D;
    .l1
    {
      font-family : Franklin Gothic Medium;
      font-size : 68px;
      color : #DCFFFA;
      color : rgb(220, 255, 250);
      text-align: center;
      top: 10px;
      position: relative;
    }
    #spin-to-unlock
    {
    //   background-image : url("/assets/slide-to-unlock.png");
      /*To create image referenced in CSS, use 'Export Selected CSS' command.*/
    //   background-repeat : no-repeat;
    //   border: 1px solid black;
      width : 100%;
      height : 100%;
    //   background-size: contain;
      position: relative;
      touch-action: manipulation;
    }

    .bg
    {
      background : $background;
      width : 100%;
      height : calc(100% - 177px);
      display: flex;
      flex-flow: column nowrap;
      align-items: center;
      justify-content: flex-start;
      
    }
    
    header
    {
      width : 100%;
      height : 177px;
      background: $background url("/assets/header-flag.png");
      background-size: contain;
    }
    
    .screen{
        width: 100%;
        height: 100%;
    }
    #unlocked{
        background: #A31735;
        overflow: hidden;
    }

#unlocked.screen
    .l1 UNLOCKED
#lock.screen
    %header
        #logo.l1 FIDGET
    .bg
        %canvas#spin-to-unlock
        
    
        

app/views/illustrator/mockup.html.haml
:scss
    #g-mockups-box .g-artboard {
        margin:0 auto;
    }
    #g-mockups-box .g-artboard p {
        margin:0;
    }
    .g-aiAbs {
        position:absolute;
    }
    .g-aiImg {
        display:block;
        width:100% !important;
    }
    .g-aiPointText p { white-space: nowrap; }
    #g-mockups-Artboard_1 {
        position:relative;
        overflow:hidden;
        width: 375px;
    }
    #g-mockups-Artboard_1 p {
        font-family:"FranklinGothic-Medium",arial,helvetica,sans-serif;
        font-size:69px;
        line-height:82px;
        filter:alpha(opacity=100);
        -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
        opacity:1;
        letter-spacing:0em;
        text-align:left;
        color:rgb(220,255,250);
        text-transform:none;
        padding-bottom:0;
        padding-top:0;
        mix-blend-mode:normal;
        font-style:normal;
    }
#g-mockups-box.ai2html
    #g-mockups-Artboard_1.g-artboard.g-artboard-v3{"data-min-width" => "375"}
        %img#g-ai0-0.g-aiImg{:src => "/assets/mockups-Artboard_1.svg"}
        #app-title.g-unlock-screen.g-aiAbs.g-aiPointText{:style => "top:10.5956%;margin-top:-45.7px;left:21.6952%;width:214px;"}
            %p FIDGET

app/views/illustrator/mockuphand.html.haml
:scss
    $background: #00A79D;
    #logo
    {
      font-family : Franklin Gothic Medium;
      font-size : 68px;
      color : #DCFFFA;
      color : rgb(220, 255, 250);
      text-align: center;
      top: 10px;
      position: relative;
    }
    #slide-to-unlock
    {
      background-image : url("/assets/slide-to-unlock.png");
      /*To create image referenced in CSS, use 'Export Selected CSS' command.*/
      background-repeat : no-repeat;
      width : 301px;
      height : 272px;
      background-size: contain;
      top: 42px;
      position: relative;
    }

    .bg
    {
      background : $background;
      width : 100%;
      height : calc(100% - 177px);
      display: flex;
      flex-flow: column nowrap;
      align-items: center;
      justify-content: flex-start;
      
    }
    
    header
    {
      width : 100%;
      height : 177px;
      background: $background url("/assets/header-flag.png");
      background-size: contain;
    }
    

%header
    #logo FIDGET
.container.bg
    #slide-to-unlock
        
    
        

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Workspace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    - controller = params[:controller]
    - if controller != 'application'
      = stylesheet_link_tag    controller, media: 'all', 'data-turbolinks-track' => true
      = javascript_include_tag controller, 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{name:"viewport", content: "user-scalable=no, width=device-width, initial-scale=1"}

  %body
    = yield